#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --archive-areas "main non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet systemd.show_status=yes live-config.username=root live-config.user-default-groups=root,seat,tty,video,render,input" \
  --bootappend-live-failsafe "boot=live components noapic noapm nodma nomce nolapic nomodeset nosmp vga=normal live-config.username=root" \
  --iso-application "Pancake Desktop Environment Live" \
  --iso-publisher "Pancake DE" \
  --iso-volume "PANCAKE_DEBIAN" \
  "${@}"
