<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pancake.Cn\Pancake.Cn.csproj" />
    <ProjectReference Include="..\Pancake.Shell\Pancake.Shell.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGLES" Version="2.23.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
