<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NWayland" Version="0.12.5" />
    <PackageReference Include="NWayland.Protocols.Wlr" Version="0.12.5" />
    <PackageReference Include="NWayland.Server" Version="0.12.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pancake.Shell\Pancake.Shell.csproj" />
  </ItemGroup>

</Project>
